version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@raiffeisen.ru
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
